name: Update site every 2 hours

on:
  schedule:
    - cron: '0 */2 * * *'  # every 2nd hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m playwright install

    - name: Run SPAR scraper
      run: python index.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add index.html
        git diff --cached --quiet || git commit -m "Update site with new data"
        git push
